"""empty message

Revision ID: 29eaffe8a486
Revises: f3318b5b109a
Create Date: 2022-08-16 00:12:56.164568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29eaffe8a486'
down_revision = 'f3318b5b109a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('checker_view', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'checker_view')
    # ### end Alembic commands ###
