"""empty message

Revision ID: 319672a4a097
Revises: 796c8870891d
Create Date: 2022-08-14 17:40:06.411219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319672a4a097'
down_revision = '796c8870891d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('color', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'color')
    # ### end Alembic commands ###
