"""empty message

Revision ID: 796c8870891d
Revises: f2aa1da5986f
Create Date: 2022-08-14 17:17:38.662788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796c8870891d'
down_revision = 'f2aa1da5986f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('register_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_register_time'), 'user', ['register_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_register_time'), table_name='user')
    op.drop_column('user', 'register_time')
    # ### end Alembic commands ###
