"""empty message

Revision ID: 824a25e32500
Revises: accaa994c487
Create Date: 2022-08-15 21:15:48.288888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824a25e32500'
down_revision = 'accaa994c487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permission_role', 'permission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('permission_role', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permission_role', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('permission_role', 'permission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
