"""empty message

Revision ID: f3318b5b109a
Revises: 824a25e32500
Create Date: 2022-08-15 23:46:45.487136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3318b5b109a'
down_revision = '824a25e32500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_role', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_role', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_role', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_role', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
